"""Schema dei dati del caso: usato dal form web, dalla CLI e dagli agenti."""
from __future__ import annotations

TIPOLOGIE = ["ufficio", "commercio", "ristorazione", "officina/produzione", "deposito/magazzino", "ricettivo",
             "sanitario", "scuola", "spettacolo/intrattenimento", "autorimessa"]

# (chiave, etichetta, tipo, gruppo, aiuto)
CAMPI = [
    ("ragione_sociale", "Ragione sociale", "text", "Anagrafica", ""),
    ("indirizzo", "Sede / unità produttiva (indirizzo, CAP, comune, prov.)", "text", "Anagrafica", ""),
    ("ateco", "Codice ATECO", "text", "Anagrafica", "Non è usato come proxy di pericolosità (metodologia VRI)"),
    ("datore_lavoro", "Datore di lavoro", "text", "Figure", ""),
    ("rspp", "RSPP (nome — studio/società)", "text", "Figure", ""),
    ("rls", "RLS", "text", "Figure", ""),
    ("attivita_descrizione", "Attività svolta (cosa avviene realmente)", "area", "Attività", "Descrizione reale, non denominazione commerciale"),
    ("tipologia_attivita", "Tipologia/e di attività", "multi", "Attività", ""),
    ("lavorazioni_rischio", "Lavorazioni con rischio specifico (saldatura, verniciatura, fiamme libere…)", "area", "Attività", ""),
    ("orari", "Orari / turni / giorni festivi", "text", "Attività", ""),
    ("fuori_orario", "Presenza fuori orario presidiato (pulizie, ricariche, sistemi automatici)", "text", "Attività", ""),
    ("variabilita", "Variabilità stagionale o per commessa", "text", "Attività", ""),
    ("aperta_pubblico", "Attività aperta al pubblico", "bool", "Attività", ""),
    ("eventi_intrattenimento", "Si svolgono eventi/intrattenimento (musica dal vivo, DJ, karaoke, spettacoli)", "bool", "Attività", "Ristoranti/bar: vedi V.15.1 c.2 lett. b e n. 65 DPR 151"),
    ("ingresso_pagamento", "Ingresso a pagamento agli eventi", "bool", "Attività", ""),
    ("pista_ballo", "Pista da ballo allestita / attività danzanti", "bool", "Attività", ""),
    ("palco_spettatori", "Palco o area spettatori strutturata", "bool", "Attività", ""),
    ("eventi_solo_aperto", "Eventi solo temporanei all'aperto (non in locale chiuso)", "bool", "Attività", "Esclusi dal n. 65 se manifestazioni temporanee"),
    ("attivita_speciale", "Attività «speciale» ai fini della formazione (livello 3)", "bool", "Documento", "Es. grandi affollamenti/attività complesse: forza il Livello 3"),
    ("confini", "Confini e interferenze (compartimentazioni, attività limitrofe)", "area", "Attività", ""),
    ("superficie_mq", "Superficie lorda complessiva [m²]", "num", "Dimensioni", "Da rilievo/planimetria"),
    ("piani_n", "Numero di piani", "num", "Dimensioni", ""),
    ("quota_min", "Quota piano più basso [m] rispetto al piano di riferimento VVF", "num", "Dimensioni", "Negativa se interrato"),
    ("quota_max", "Quota piano più alto [m]", "num", "Dimensioni", ""),
    ("sup_compartimento_max", "Superficie del compartimento maggiore [m²]", "num", "Dimensioni", "Se assente = superficie complessiva (cautelativo)"),
    ("occupanti_lavoratori", "Lavoratori dipendenti [n.]", "num", "Affollamento", ""),
    ("occupanti_appaltatori", "Lavoratori di terzi/appaltatori abituali [n.]", "num", "Affollamento", ""),
    ("occupanti_terzi", "Pubblico/clienti/visitatori contemporanei [n.]", "num", "Affollamento", ""),
    ("occupanti_picco", "Picco stagionale/occasionale [n.]", "num", "Affollamento", "Se maggiore del totale, prevale"),
    ("posti_letto", "Posti letto [n.]", "num", "Affollamento", ""),
    ("disabili_prevalenti", "Occupanti prevalentemente con disabilità", "bool", "Affollamento", ""),
    ("occupanti_familiari", "Occupanti familiari con i luoghi (lavoratori)", "bool", "Affollamento", "Se pubblico presente, δocc = B"),
    ("qf_mj_m2", "Carico d'incendio specifico qf [MJ/m²]", "num", "Combustibili", "Vuoto = stima tabellare (Percorso A) o calcolo dai materiali (Percorso B)"),
    ("sostanze_significative", "Sostanze/miscele pericolose in quantità significative", "bool", "Combustibili", ""),
    ("lavorazioni_pericolose", "Lavorazioni pericolose ai fini dell'incendio", "bool", "Combustibili", ""),
    ("litri_infiammabili", "Liquidi infiammabili [L]", "num", "Combustibili", ""),
    ("kg_carta", "Carta/cartone in deposito [kg]", "num", "Combustibili", ""),
    ("kg_legno", "Legno in deposito [kg]", "num", "Combustibili", ""),
    ("kg_plastica", "Plastica/gomma in deposito [kg]", "num", "Combustibili", ""),
    ("kw_termico", "Potenza impianti termici [kW]", "num", "Impianti", ""),
    ("cucina_cottura", "Cucina con apparecchi di cottura (classe F)", "bool", "Impianti", ""),
    ("soggetta_dpr151", "Attività soggetta a controllo VVF (DPR 151/2011)", "tri", "Quadro normativo", "Vuoto = lo stabilisce l'agente normativo; indicare Sì/No per forzare"),
    ("voce_dpr151", "Voce Allegato I DPR 151/2011 (se soggetta)", "text", "Quadro normativo", ""),
    ("categoria_dpr151", "Categoria A/B/C", "text", "Quadro normativo", ""),
    ("rtv_applicabile", "RTV del Codice (Sez. V) applicabile — quale", "text", "Quadro normativo", "Es. V.15 locali di trattenimento"),
    ("rt_settore", "Regola tecnica di settore pre-Codice applicabile — quale", "text", "Quadro normativo", ""),
    ("vincolata", "Attività/ambito vincolato per arte o storia", "bool", "Rischi Rbeni/Rambiente", ""),
    ("strategica", "Attività strategica", "bool", "Rischi Rbeni/Rambiente", ""),
    ("ricettori_sensibili", "Ricettori sensibili esterni / materiali D.Lgs. 152/2006 rilevanti", "bool", "Rischi Rbeni/Rambiente", ""),
    ("n_uscite", "Uscite indipendenti presenti [n.]", "num", "Rilievo in sito", "Per verifica automatica S.4"),
    ("lcc_misurata", "Corridoio cieco massimo misurato [m]", "num", "Rilievo in sito", ""),
    ("les_misurata", "Lunghezza di esodo massima misurata [m]", "num", "Rilievo in sito", "A filo teso"),
    ("largh_installata_mm", "Larghezza minima vie/uscite installata [mm]", "num", "Rilievo in sito", ""),
    ("n_estintori", "Estintori classe A presenti [n.]", "num", "Rilievo in sito", ""),
    ("dalfa_override", "δα imposto dal tecnico (1–4)", "num", "Parametri imposti", "Lasciare vuoto per la stima cautelativa dell'app"),
    ("rvita_override", "Rvita imposto dal tecnico (es. B2)", "text", "Parametri imposti", ""),
    ("dvr_data", "Data ultima revisione DVR", "text", "Raccordi", ""),
    ("dvr_sezioni", "Sezioni del DVR collegate", "text", "Raccordi", ""),
    ("pe_rif", "Riferimento Piano di Emergenza (rev./data)", "text", "Raccordi", ""),
    ("comando_vvf", "Comando VVF competente", "text", "Pratica VVF (se soggetta)", ""),
    ("voce_dpr151_desc", "Voce Allegato I — descrizione", "text", "Pratica VVF (se soggetta)", "Es. 74.1.C — Impianti di produzione calore >116 kW"),
    ("tipo_procedimento", "Tipo di procedimento (CPI / SCIA / attestazione rinnovo)", "text", "Pratica VVF (se soggetta)", ""),
    ("estremi_pratica", "Estremi pratica (prot. e data)", "text", "Pratica VVF (se soggetta)", ""),
    ("data_cpi", "Data rilascio CPI / presentazione SCIA", "text", "Pratica VVF (se soggetta)", "gg/mm/aaaa"),
    ("periodicita_rinnovo", "Periodicità rinnovo [anni]", "num", "Pratica VVF (se soggetta)", "5 o 10"),
    ("scadenza_rinnovo", "Scadenza prossimo rinnovo", "text", "Pratica VVF (se soggetta)", "gg/mm/aaaa"),
    ("professionista_antincendio", "Professionista antincendio di riferimento (n. iscrizione MI)", "text", "Pratica VVF (se soggetta)", ""),
    ("tel_fisso", "Telefono fisso unità produttiva", "text", "Piano di emergenza", ""),
    ("tel_mobile", "Telefono mobile responsabile", "text", "Piano di emergenza", ""),
    ("email_azienda", "E-mail", "text", "Piano di emergenza", ""),
    ("asl_ats", "ASL/ATS competente (denominazione e tel.)", "text", "Piano di emergenza", ""),
    ("rspp_tel", "RSPP — telefono ed e-mail", "text", "Piano di emergenza", ""),
    ("coord_diurno", "Coordinatore emergenza turno diurno (nome — tel.)", "text", "Piano di emergenza", ""),
    ("coord_notturno", "Coordinatore emergenza notturno/fuori orario (nome — tel.) o N.A.", "text", "Piano di emergenza", ""),
    ("medico_competente", "Medico competente", "text", "Piano di emergenza", ""),
    ("sistema_gestione", "Sistema di gestione adottato (ISO 45001 / UNI-INAIL / MOG 231 / Nessuno)", "text", "Piano di emergenza", ""),
    ("irai_presente", "Impianto IRAI presente", "bool", "Piano di emergenza", ""),
    ("irai_ubicazione", "Ubicazione centrale IRAI", "text", "Piano di emergenza", ""),
    ("irai_ditta", "Ditta manutenzione IRAI (nome — tel.)", "text", "Piano di emergenza", ""),
    ("punto_raccolta", "Punto di raccolta principale", "text", "Piano di emergenza", ""),
    ("punto_raccolta_alt", "Punto di raccolta alternativo", "text", "Piano di emergenza", ""),
    ("ub_gas", "Ubicazione intercettazione gas", "text", "Piano di emergenza", ""),
    ("ub_elettrico", "Ubicazione sezionamento elettrico generale", "text", "Piano di emergenza", ""),
    ("ub_ventilazione", "Ubicazione sezionamento ventilazione/climatizzazione", "text", "Piano di emergenza", ""),
    ("ub_acqua", "Ubicazione intercettazione acqua", "text", "Piano di emergenza", ""),
    ("n_interrati", "Piani interrati [n.]", "num", "Piano di emergenza", ""),
    ("altezza_antincendio", "Altezza antincendio [m]", "num", "Piano di emergenza", ""),
    ("n_idranti", "Idranti/naspi [n.]", "num", "Piano di emergenza", ""),
    ("sprinkler", "Impianto sprinkler presente", "bool", "Piano di emergenza", ""),
    ("illuminazione_autonomia_min", "Autonomia illuminazione di emergenza [min]", "num", "Piano di emergenza", ""),
    ("tel_antiveleni", "Centro antiveleni — n.", "text", "Numeri utili", ""),
    ("tel_antiustioni", "Centro antiustioni — n.", "text", "Numeri utili", ""),
    ("tel_gas", "Distributore gas — n.", "text", "Numeri utili", ""),
    ("tel_elettricita", "Distributore elettricità — n.", "text", "Numeri utili", ""),
    ("tel_acqua", "Distributore acqua — n.", "text", "Numeri utili", ""),
    ("tel_impiantista", "Impiantista elettrico — n.", "text", "Numeri utili", ""),
    ("tel_protezione_civile", "Protezione Civile/Prefettura — n.", "text", "Numeri utili", ""),
    ("tel_referente", "Gestore/referente emergenza (nome — tel.)", "text", "Numeri utili", ""),
    ("data_emissione", "Data di emissione", "text", "Documento", "gg/mm/aaaa"),
    ("revisione", "Revisione n.", "text", "Documento", "Es. 00"),
    ("redatto_da", "Redatto da", "text", "Documento", ""),
    ("periodicita_revisione", "Periodicità revisione ordinaria [anni]", "num", "Documento", ""),
]
TIPI = {k: t for k, _, t, _, _ in CAMPI}


# liste strutturate (editor a tabella nell'interfaccia)
LISTE = {
    "locali": {"label": "Locali / aree (VRI-4.1)", "colonne": [("nome", "Locale/area", "text"), ("mq", "m²", "num"), ("dest", "Destinazione d'uso", "text"), ("tipo", "Tipologia (es. ufficio, ristorazione, ricettivo)", "text"), ("occ", "Occupanti", "num")]},
    "sostanze_dettaglio": {"label": "Materiali e sostanze per area (VRI-5)", "colonne": [("area", "Area", "text"), ("nome", "Sostanza/materiale", "text"), ("quantita", "Quantità", "text"), ("unita", "Unità", "text"), ("stoccaggio", "Stoccaggio", "text"), ("modalita", "Modalità d'uso", "text"), ("rilevanza", "Rilevanza (alta/media/bassa)", "text")]},
    "storico_revisioni": {"label": "Registro delle revisioni", "colonne": [("rev", "Rev.", "text"), ("data", "Data", "text"), ("redatto", "Redatto da", "text"), ("descrizione", "Descrizione della modifica", "text")]},
    "addetti": {"label": "Addetti alle emergenze (PE-5.3)", "colonne": [("nome", "Nominativo", "text"), ("turno", "Turno/orario", "text"), ("coord", "Coord.", "bool"), ("ai", "A.I.", "bool"), ("ps", "P.S.", "bool"), ("ge", "G.E.", "bool"), ("as", "A.S.", "bool"), ("tel", "Telefono", "text")]},
}
